name: Test

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libgl1-mesa-dev xorg-dev
      - name: test
        run: |
          go test ./... -race -coverprofile=coverage.txt.tmp -covermode=atomic
          grep -v "_easyjson.go" coverage.txt.tmp > coverage.txt
      - uses: codecov/codecov-action@v3
        with:
          file: coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}
